name = "ficasa-backend"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "FICASA_JOBS"
id = "640f2520e63f45e8b61674c8b015ac22"

[[kv_namespaces]]
binding = "FICASA_RESULTS"
id = "6c30258e4d0a4510b42044e97e3a2ef1"

[[queues.producers]]
queue = "ficasa-queue"
binding = "FICASA_QUEUE"

[[queues.consumers]]
queue = "ficasa-queue"
